
language: csharp

sudo: required
services:
  - docker

# Caches Nuget packages
cache:
    directories:
        - ~/.nuget/packages

before_install:
    # Build a docker image named webapp:test from a docker file placed in ./docker directory.
    - openssl aes-256-cbc -K $encrypted_27448686ddb4_key -iv $encrypted_27448686ddb4_iv -in digital-ocean-agile.enc -out keys/digital-ocean-agile -d
    - eval "$(ssh-agent -s)"
    - chmod 600 ~/.ssh/digital-ocean-for-agile-course
    - ssh-add ~/.ssh/digital-ocean-for-agile-course
    - docker build -t webapp:test -f ./dockerfile/test .

script:
    # Run (or create) a container from webapp:test docker image
    # Bind nuget packages directory
    - docker run -it --rm -v $PWD/publish:/root/publish -v ~/.nuget/packages:/root/.nuget/packages webapp:test

after_success:
    - chmod +x $PWD/scripts/travis-ci.sh
    - $PWD/scripts/travis-ci.sh
    - scp -o StrictHostKeyChecking=no ./scripts/get-release-from-dockerhub-and-start.sh u1442881@159.203.33.172:~/
    - scp -r -o StrictHostKeyChecking=no $HOME/publish u1442881@159.203.33.172:~/publish 
    - ssh u1442881@159.203.33.172 "chmod +x get-release-from-dockerhub-and-start.sh"
    - ssh u1442881@159.203.33.172 "sh get-release-from-dockerhub-and-start.sh"