
language: csharp

sudo: required
services:
  - docker

# Caches Nuget packages
cache:
    directories:
        - ~/.nuget/packages

before_install:
    # Build a docker image named webapp:test from a docker file placed in ./docker directory.
    - docker build -t webapp:test -f ./dockerfile/test .

script:
    # Run (or create) a container from webapp:test docker image
    # Bind nuget packages directory
    - docker run -it --rm -v ~/publish:/root/publish -v ~/.nuget/packages:/root/.nuget/packages webapp:test